spring:
  application:
    # =============================
    # APPLICATION NAME
    # =============================
    name: OTP-MICROSERVICE
  # =============================
  # DATASOURCE CONFIG
  # =============================
  data:
    jpa:
      repositories:
        enabled: false
    # =============================
    # REST DATA CONFIG
    # =============================
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/otp?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: toortoor
    hikari:
      auto-commit: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # =======================================================================
      # AUTO UPDATE DATABASE SCHEMA (Not Recommended In Production Environment)
      # =======================================================================
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  # =======================================================================
  # MAILING CONFIG
  # =======================================================================
  mail:
    host: smtp.gmail.com
    password: caytmymzlhuzlisg
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender: HAYTHAM DAHRI
    username: haytham.dahri@gmail.com

org:
  technologia:
    jwt:
      # =============================
      # JWT Secret
      # =============================
      secret: Technologi@8520__PT_!???
